# Datos para el sito
title: Wendylu
markdown: kramdown
url: "https://wendyar.github.io"
baseurl: "/wendyar"
exlude: ['README.md']
description: Mi nombre es Wendy Argente  este es un blog personal donde comparto proyectos universitarios de mi carrera de ingeniería en Telemática.
keywords: universidad abierta y a distancia de méxico, telemática, autodidácta, proyectos, universidad, ingeniería, unadm, wendy, argente


# Mis datos
autor: Wendy Magaña Argente
imagen_personal: wendylu.jpg
autor_descripcion: Actualmente soy una estudiante de la Ingeniería en Telemática y he creado este espacio para documentar y almacenar mis proyectos de vida.
#email: es1611300455@gmail.com
email_personal: wargente_10@outlook.com


# Para redes sociales
usuario_github: wendyar
#usuario_facebook: "LADSG"
#usuario_twitter: _AngelGuerrero_

# Para el sistema
permalink: none
